// =========================================================================
// MASTER ZANPAKUTŌ CATALOG — 50 CANONICAL SOUL ARCHETYPES (ZGE V5.0)
// =========================================================================

const MASTER_ZANPAKUTO_CATALOG = [
  {
    id: "zk-01-kurotsubaki",
    nome: "Kurotsubaki",
    kanji: "黒椿",
    traducao: "Camélia Negra",
    elemento: "Inércia, Pétalas Negras & Absorção Cinética",
    comando: "Floresça no silêncio, Kurotsubaki",
    espirito: "Uma mulher alta, de aparência madura, vestida com um quimono preto coberto por pétalas de camélia. Seu rosto é parcialmente escondido por um véu. Ela passa a maior parte do tempo sentada em um jardim completamente sem cor, cuidando de uma única árvore.",
    formaSelada: "Katana de guarda circular no formato de flor de camélia e bainha de laca negra fosca.",
    formatoArma: "Espada fina e negra com guarda circular semelhante a uma flor. Pétalas negras suspensas no ar.",
    poder: "Jardim do Último Instante: As pétalas absorvem o movimento de qualquer coisa que tocam. Golpes perdem velocidade e flechas quase param. Limite: as pétalas só armazenam uma quantidade limitada de movimento antes de desaparecerem.",
    limitacoes: "Capacidade máxima de absorção por pétala; exige reposicionamento para cobrir ângulos.",
    bankaiNome: "Kurotsubaki — Shūen Teien",
    bankaiKanji: "黒椿・終焉庭園",
    bankaiTraducao: "Jardim do Fim",
    bankaiComando: "Bankai — Kurotsubaki, Shūen Teien!",
    bankaiForma: "Todas as pétalas se transformam em árvores negras gigantescas. O campo vira um jardim silencioso.",
    bankaiPoder: "Redistribuição Cinética Total: Retira velocidade de ataques e movimentos inimigos e transfere instantaneamente para os golpes e estocadas do usuário.",
    bankaiLimitacoes: "Exige que o usuário mantenha o equilíbrio cinético entre absorção e liberação.",
    indices: { potencia: 8, alcance: 9, complexidade: 7, versatilidade: 8, custo: 6 }
  },
  {
    id: "zk-02-akagane",
    nome: "Akagane",
    kanji: "赤鋼",
    traducao: "Aço Vermelho",
    elemento: "Metalurgia Cinética & Armadura de Impacto",
    comando: "Forje aquilo que ainda não existe, Akagane",
    espirito: "Um ferreiro gigantesco sem rosto, com o corpo coberto por placas metálicas e um enorme avental. Em vez de mãos, possui martelos. Ele nunca fala; responde apenas golpeando uma bigorna.",
    formaSelada: "Lâmina pesada de aço avermelhado com acabamento rústico de forja.",
    formatoArma: "Placas metálicas vermelhas que envolvem o braço direito, formando manopla e antebraço blindado.",
    poder: "Memória do Impacto: Cada golpe recebido pela armadura acumula energia cinética para ser liberada no próximo ataque. Se acumular em excesso sem golpear, a armadura sobrecarrega o usuário.",
    limitacoes: "Necessidade de receber impactos para carregar; risco de sobrecarga se não descarregar.",
    bankaiNome: "Akagane — Hyakurenro",
    bankaiKanji: "赤鋼・百錬炉",
    bankaiTraducao: "Forja das Cem Temperas",
    bankaiComando: "Bankai — Akagane, Hyakurenro!",
    bankaiForma: "Armadura completa cobrindo todo o corpo com uma enorme fornalha espiritual acesa nas costas.",
    bankaiPoder: "Refino de Energia: Converte a energia acumulada dos impactos recebidos diretamente em força, velocidade, resistência ou impulso contínuo enquanto se mantém lutando.",
    bankaiLimitacoes: "A energia se dissipa se o usuário interromper o combate por muito tempo.",
    indices: { potencia: 9, alcance: 4, complexidade: 6, versatilidade: 8, custo: 7 }
  },
  {
    id: "zk-03-suisen",
    nome: "Suisen",
    kanji: "水仙",
    traducao: "Narciso",
    elemento: "Espelhos Líquidos & Ilusão de Movimento",
    comando: "Olhe para si mesmo, Suisen",
    espirito: "Um garoto extremamente pálido, vestido como um bailarino, que vive em um salão cheio de espelhos cobertos por água.",
    formaSelada: "Katana elegante com acabamento prateado espelhado e tsuba translúcida.",
    formatoArma: "Espada extremamente fina e prateada com lâmina de aspecto líquido que distorce reflexos.",
    poder: "Reflexo Falso: Cria cópias ilusórias de movimentos recém-realizados para confundir a percepção do adversário.",
    limitacoes: "As cópias não possuem massa ou dano real, servindo como distração perceptiva.",
    bankaiNome: "Suisen — Senkyō Kairō",
    bankaiKanji: "水仙・千鏡回廊",
    bankaiTraducao: "Corredor das Mil Imagens",
    bankaiComando: "Bankai — Suisen, Senkyō Kairō!",
    bankaiForma: "O campo se transforma em um enorme corredor de espelhos líquidos flutuantes.",
    bankaiPoder: "Troca Espelho-Posicional: O usuário pode trocar de posição quase que instantaneamente com qualquer reflexo criado no campo de batalha.",
    bankaiLimitacoes: "Cada troca consome e destrói o espelho utilizado.",
    indices: { potencia: 6, alcance: 8, complexidade: 8, versatilidade: 9, custo: 5 }
  },
  {
    id: "zk-04-hoshikuzu",
    nome: "Hoshikuzu",
    kanji: "星屑",
    traducao: "Poeira Estelar",
    elemento: "Órbitas Luminosas & Trajetória Curva",
    comando: "Desperte no céu, Hoshikuzu",
    espirito: "Uma pequena criatura humanoide coberta por um manto azul-escuro contendo um céu estrelado.",
    formaSelada: "Wakizashi fina com detalhes estelares dourados no cabo.",
    formatoArma: "Dezenas de pequenos cristais luminosos que orbitam o usuário em trajetórias curvas impossíveis.",
    poder: "Órbita: Fragmentos que alteram trajetórias de voo no ar e traçam linhas de corte não-lineares.",
    limitacoes: "Exige cálculo mental contínuo para manter os cristais em órbita harmônica.",
    bankaiNome: "Hoshikuzu — Tenkan",
    bankaiKanji: "星屑・天環",
    bankaiTraducao: "Anel Celestial",
    bankaiComando: "Bankai — Hoshikuzu, Tenkan!",
    bankaiForma: "Enormes anéis orbitais luminosos cobrindo todo o céu da área de batalha.",
    bankaiPoder: "Controle Gravitacional de Trajetória: Define pontos de atração orbital que curvam qualquer projétil, golpe ou deslocamento que entre no anel.",
    bankaiLimitacoes: "Controla a trajetória, mas não anula a força bruta do projétil.",
    indices: { potencia: 7, alcance: 9, complexidade: 8, versatilidade: 9, custo: 6 }
  },
  {
    id: "zk-05-koriame",
    nome: "Kōriame",
    kanji: "氷雨",
    traducao: "Chuva Congelada",
    elemento: "Inércia Hidráulica & Resistência Direcional",
    comando: "Chore sobre este mundo, Kōriame",
    espirito: "Uma senhora idosa carregando um guarda-chuva branco com expressão melancólica sob chuva eterna.",
    formaSelada: "Katana com guarda em forma de cúpula de guarda-chuva dobrada.",
    formatoArma: "Guarda-chuva metálico branco com ponta afiada, invocando precipitação espiritual contínua.",
    poder: "Gotas de Peso: Cada gota espiritual que atinge um alvo aumenta sua inércia e dificulta a aceleração.",
    limitacoes: "O efeito é gradual e depende do tempo de exposição do alvo à chuva.",
    bankaiNome: "Kōriame — Hakusōten",
    bankaiKanji: "氷雨・白葬天",
    bankaiTraducao: "Céu do Funeral Branco",
    bankaiComando: "Bankai — Kōriame, Hakusōten!",
    bankaiForma: "Céu escurecido cobrindo quilômetros com cortinas torrenciais de chuva congelada.",
    bankaiPoder: "Manipulação Direcional de Resistência: O usuário escolhe quais eixos espaciais possuem resistência esmagadora (ex: avançar para frente fica pesado, recuar fica rápido).",
    bankaiLimitacoes: "Afeta a física espacial de todos no campo, exigindo planejamento posicional do usuário.",
    indices: { potencia: 8, alcance: 10, complexidade: 8, versatilidade: 8, custo: 7 }
  },
  {
    id: "zk-06-kagamibana",
    nome: "Kagamibana",
    kanji: "鏡花",
    traducao: "Flor do Espelho",
    elemento: "Possibilidade Imediata & Fragmentos de Vidro",
    comando: "Reflita aquilo que deveria ser esquecido, Kagamibana",
    espirito: "Uma mulher sem olhos com flores de vidro crescendo pelos cabelos dentro de uma estufa quebrada.",
    formaSelada: "Katana com lâmina de reflexo fragmentado como mosaico de espelho.",
    formatoArma: "Espada transparente com lâmina de vidro espiritual que projeta imagens alternativas de momentos.",
    poder: "Fragmento de Possibilidade: Cria uma pequena distorção imediata onde o usuário escolhe entre o acontecimento real e a imagem alternativa nos próximos segundos.",
    limitacoes: "Duração de poucos segundos e curto alcance.",
    bankaiNome: "Kagamibana — Banshō Shakai",
    bankaiKanji: "鏡花・万象写界",
    bankaiTraducao: "Mundo que Copia Todas as Coisas",
    bankaiComando: "Bankai — Kagamibana, Banshō Shakai!",
    bankaiForma: "O ambiente se cristaliza em uma imensa superfície espelhada.",
    bankaiPoder: "Colapso de Múltiplas Possibilidades: Cria simultaneamente 3 a 5 desfechos possíveis para uma mesma ação, colapsando a mais vantajosa na realidade.",
    bankaiLimitacoes: "Apenas uma possibilidade pode se materializar de fato.",
    indices: { potencia: 8, alcance: 8, complexidade: 10, versatilidade: 9, custo: 8 }
  },
  {
    id: "zk-07-mukade",
    nome: "Mukade",
    kanji: "百足",
    traducao: "Centopeia",
    elemento: "Encadeamento de Lâminas & Correntes Sequenciais",
    comando: "Multiplique-se pelo caminho, Mukade",
    espirito: "Uma criatura longa com dezenas de braços segurando espadas e máscara de crânio de inseto.",
    formaSelada: "Katana segmentada com ranhuras visíveis ao longo do fio.",
    formatoArma: "Espada dividida em múltiplas lâminas menores conectadas por correntes articuladas.",
    poder: "Ataque Encadeado: Cada golpe conectado reposiciona imediatamente a lâmina seguinte em novo ângulo de ataque.",
    limitacoes: "Se errar a sequência, todas as lâminas retornam ao ponto de origem.",
    bankaiNome: "Mukade — Mukyū Renjin",
    bankaiKanji: "百足・無窮連刃",
    bankaiTraducao: "Lâminas da Corrente Infinita",
    bankaiComando: "Bankai — Mukade, Mukyū Renjin!",
    bankaiForma: "Rede gigante de milhares de lâminas articuladas operando em malha tridimensional.",
    bankaiPoder: "Encadeamento Autônomo Infinito: A Bankai prevê e executa cadeias ininterruptas de ataques automáticos baseados no último movimento.",
    bankaiLimitacoes: "Se o adversário quebrar o ritmo ou ler o padrão geométrico, a rede perde tração.",
    indices: { potencia: 8, alcance: 7, complexidade: 7, versatilidade: 8, custo: 6 }
  },
  {
    id: "zk-08-yureiishi",
    nome: "Yūreiishi",
    kanji: "幽霊石",
    traducao: "Pedra Fantasma",
    elemento: "Âncoras Espirituais & Transição Espacial",
    comando: "Permaneça onde ninguém pode tocar, Yūreiishi",
    espirito: "Uma criança semitransparente sentada sobre uma enorme rocha flutuante com espíritos menores.",
    formaSelada: "Tantō negra com pedra de obsidiana cravada no pomo.",
    formatoArma: "A lâmina se dissolve em 4 pequenas pedras negras orbitais.",
    poder: "Âncoras Espirituais: O usuário fixa as pedras no cenário e pode retornar instantaneamente para a posição de qualquer uma delas.",
    limitacoes: "Número limitado de âncoras e distância máxima definida.",
    bankaiNome: "Yūreiishi — Hyakki Kyō",
    bankaiKanji: "幽霊石・百鬼境",
    bankaiTraducao: "Território das Cem Almas",
    bankaiComando: "Bankai — Yūreiishi, Hyakki Kyō!",
    bankaiForma: "Centenas de pedras negras flutuando e formando uma matriz dimensional densa no campo.",
    bankaiPoder: "Malha de Salto Instantâneo: Permite saltos sucessivos entre centenas de pontos conectados no espaço.",
    bankaiLimitacoes: "Grandes distâncias aumentam proporcionalmente o desgaste de Reiatsu.",
    indices: { potencia: 6, alcance: 9, complexidade: 8, versatilidade: 10, custo: 7 }
  },
  {
    id: "zk-09-raimei",
    nome: "Raimei",
    kanji: "雷鳴",
    traducao: "Trovão",
    elemento: "Ressonância Harmônica & Vibração Sônica",
    comando: "Faça o céu responder, Raimei",
    espirito: "Um gigante usando máscara de teatro tradicional coberto por linhas luminosas como rachaduras.",
    formaSelada: "Katana com lâmina em zigue-zague sutil e tsuba de bronze martelado.",
    formatoArma: "Lâmina irregular em formato de raio com cabo que emite pulsos luminosos rítmicos.",
    poder: "Ressonância: Movimentos executados no mesmo compasso acumulam ondas vibratórias para um golpe devastador.",
    limitacoes: "Exige precisão métrica de tempo; se o ritmo for interrompido, a carga dissipa.",
    bankaiNome: "Raimei — Gōtenritsu",
    bankaiKanji: "雷鳴・轟天律",
    bankaiTraducao: "Lei do Céu Trovejante",
    bankaiComando: "Bankai — Raimei, Gōtenritsu!",
    bankaiForma: "O campo inteiro reverbera ondas sônicas com anéis de ressonância no solo e no céu.",
    bankaiPoder: "Harmonia de Batalha: Cada ação executada no compasso espiritual do usuário ganha potência e velocidade multiplicadas.",
    bankaiLimitacoes: "Perder o ritmo zera a ressonância acumulada.",
    indices: { potencia: 9, alcance: 7, complexidade: 8, versatilidade: 7, custo: 6 }
  },
  {
    id: "zk-10-shirogane",
    nome: "Shirogane",
    kanji: "白銀",
    traducao: "Prata Branca",
    elemento: "Equilíbrio de Forças & Balança Tática",
    comando: "Pese aquilo que existe, Shirogane",
    espirito: "Um cavaleiro sem rosto em armadura branca polida segurando uma balança colossal.",
    formaSelada: "Katana de aço prateado puro com empunhadura revestida em tecido alvo.",
    formatoArma: "Longa lâmina branca reluzente com guarda no formato de braço de balança.",
    poder: "Equilíbrio: Detecta a disparidade física entre combatentes e reduz a diferença cedendo outra vantagem.",
    limitacoes: "Não cria energia do nada; requer sacrifício equivalente de outro aspecto.",
    bankaiNome: "Shirogane — Tenbin Kai",
    bankaiKanji: "白銀・天秤界",
    bankaiTraducao: "Domínio da Balança Celestial",
    bankaiComando: "Bankai — Shirogane, Tenbin Kai!",
    bankaiForma: "Uma monumental balança dourada e prateada manifesta-se nos céus sobre o campo de batalha.",
    bankaiPoder: "Equalização Multidimensional: Transfere proporcionalmente valores entre força, velocidade, reiatsu e resiliência entre os lutadores.",
    bankaiLimitacoes: "Toda alteração exige contrapartida exata de acordo com a balança.",
    indices: { potencia: 7, alcance: 8, complexidade: 9, versatilidade: 10, custo: 7 }
  },
  {
    id: "zk-11-kurohane",
    nome: "Kurohane",
    kanji: "黒羽",
    traducao: "Asas Negras",
    elemento: "Percepção Sensorial & Penas de Informação",
    comando: "Observe aquilo que ninguém percebe, Kurohane",
    espirito: "Uma enorme coruja negra sem olhos em uma biblioteca de tomos flutuantes.",
    formatoArma: "Espada que se divide em penas negras registradoras de dados sensoriais.",
    poder: "Registro Sensorial: Penas que captam som, cheiro, temperatura e pressão espiritual ao redor.",
    bankaiNome: "Kurohane — Banshikiden",
    bankaiKanji: "黒羽・万識殿",
    bankaiTraducao: "Palácio das Mil Percepções",
    bankaiPoder: "Conexão de Percepções: Reconstrói acontecimentos recentes e antecipa intenções através das penas.",
    indices: { potencia: 6, alcance: 9, complexidade: 8, versatilidade: 9, custo: 5 }
  },
  {
    id: "zk-12-akeboshi",
    nome: "Akeboshi",
    kanji: "明星",
    traducao: "Estrela da Manhã",
    elemento: "Antecipação de Padrões & Astronomia Espiritual",
    comando: "Mostre o instante que se aproxima, Akeboshi",
    espirito: "Um astrônomo jovem com relógio sem ponteiros.",
    formatoArma: "Lâmina com círculos luminosos que rastreiam ações repetitivas do adversário.",
    poder: "Identificação de Padrão: Sinaliza o instante exato em que o inimigo repetirá um movimento.",
    bankaiNome: "Akeboshi — Senkenten",
    bankaiKanji: "明星・先見天",
    bankaiTraducao: "Céu da Visão Antecipada",
    bankaiPoder: "Previsibilidade Simultânea: Mapeia dezenas de trajetórias e padrões de combate em tempo real.",
    indices: { potencia: 7, alcance: 8, complexidade: 9, versatilidade: 9, custo: 6 }
  },
  {
    id: "zk-13-shigure",
    nome: "Shigure",
    kanji: "時雨",
    traducao: "Chuva Passageira",
    elemento: "Deterioração Estrutural & Desgaste Temporal",
    comando: "Passe como a chuva, Shigure",
    espirito: "Mulher com vestido feito de relógios quebrados.",
    formatoArma: "Lâmina que goteja chuva de aceleração de fadiga em materiais.",
    poder: "Gotas de Corrosão: Acelera o desgaste natural de metal, madeira e tecidos tocados.",
    bankaiNome: "Shigure — Hyakunen'ame",
    bankaiKanji: "時雨・百年雨",
    bankaiTraducao: "Chuva dos Cem Anos",
    bankaiPoder: "Deterioração Ambiental Seletiva: Controla a velocidade de desgaste e fadiga de tudo na área.",
    indices: { potencia: 8, alcance: 9, complexidade: 7, versatilidade: 8, custo: 7 }
  },
  {
    id: "zk-14-ginmokusei",
    nome: "Ginmokusei",
    kanji: "銀木犀",
    traducao: "Osmanthus Prateado",
    elemento: "Rastreamento Olfativo & Aromas Espirituais",
    comando: "Espalhe aquilo que os olhos não podem encontrar, Ginmokusei",
    espirito: "Uma senhora cega cuidando de um jardim invisível.",
    formatoArma: "Espada que exala perfume de rastreamento espiritual indelével.",
    poder: "Marca Olfativa: Marca alvos pelo odor de Reishi impossível de ocultar.",
    bankaiNome: "Ginmokusei — Hyakkōtei",
    bankaiKanji: "銀木犀・百香庭",
    bankaiTraducao: "Jardim das Cem Fragrâncias",
    bankaiPoder: "Rede Sensorial de Fragrâncias: Mapeia perfeitamente qualquer presença marcada em quilômetros.",
    indices: { potencia: 5, alcance: 10, complexidade: 7, versatilidade: 8, custo: 4 }
  },
  {
    id: "zk-15-tsukikage",
    nome: "Tsukikage",
    kanji: "月影",
    traducao: "Sombra Lunar",
    elemento: "Ocultação Visual & Luz e Trevas",
    comando: "Esconda aquilo que a luz revela, Tsukikage",
    espirito: "Um homem com máscara meio clara meio escura.",
    formatoArma: "Lâmina que apaga detalhes visuais específicos do alvo ou do usuário.",
    poder: "Ocultação de Detalhe: Torna armas, feridas ou membros invisíveis aos olhos.",
    bankaiNome: "Tsukikage — Mumyōkyō",
    bankaiKanji: "月影・無明境",
    bankaiTraducao: "Domínio Sem Luz",
    bankaiPoder: "Manipulação Coletiva da Percepção: Apaga seletivamente conjuntos inteiros de dados visuais.",
    indices: { potencia: 6, alcance: 8, complexidade: 8, versatilidade: 9, custo: 6 }
  },
  {
    id: "zk-16-tetsubana",
    nome: "Tetsubana",
    kanji: "鉄花",
    traducao: "Flor de Ferro",
    elemento: "Metal Vegetal & Arquitetura Espiritual",
    comando: "Floresça através da dureza, Tetsubana",
    espirito: "Uma garota pequena coberta por flores de metal.",
    formatoArma: "Lâmina que faz flores metálicas brotarem de superfícies tocadas.",
    poder: "Brotamento Metálico: Cria barreiras e pontas de aço vegetal em paredes e solos.",
    bankaiNome: "Tetsubana — Banshōtei",
    bankaiKanji: "鉄花・万象庭",
    bankaiTraducao: "Jardim das Mil Estruturas",
    bankaiPoder: "Arquitetura Espiritual Dinâmica: Ergue fortalezas e labirintos de aço orgânico instantaneamente.",
    indices: { potencia: 8, alcance: 8, complexidade: 7, versatilidade: 8, custo: 6 }
  },
  {
    id: "zk-17-usuginu",
    nome: "Usuginu",
    kanji: "薄絹",
    traducao: "Seda Delicada",
    elemento: "Separação Física & Fitas de Espaço",
    comando: "Dance entre os espaços, Usuginu",
    espirito: "Bailarina envolta em milhares de véus sem rosto.",
    formatoArma: "Fita cortante ultrafina que separa temporariamente superfícies contíguas.",
    poder: "Linha de Separação: Desconecta lâminas de cabos e portas de batentes momentaneamente.",
    bankaiNome: "Usuginu — Dankaimai",
    bankaiKanji: "薄絹・断界舞",
    bankaiTraducao: "Dança do Mundo Separado",
    bankaiPoder: "Zonas de Desconexão Espacial: Cria limites onde nada pode permanecer unido fisicamente.",
    indices: { potencia: 8, alcance: 8, complexidade: 9, versatilidade: 8, custo: 7 }
  },
  {
    id: "zk-18-suzunari",
    nome: "Suzunari",
    kanji: "鈴鳴",
    traducao: "Som dos Sinos",
    elemento: "Comunicação Sônica & Ondas de Frequência",
    comando: "Desperte através do som, Suzunari",
    espirito: "Criança com centenas de sinos tilintantes.",
    formatoArma: "Espada sonora que transmite mensagens e frequências por vibração.",
    poder: "Voz do Sino: Transmite mensagens secretas em frequências inaudíveis pelo ar.",
    bankaiNome: "Suzunari — Sen'on Kairō",
    bankaiKanji: "鈴鳴・千音回廊",
    bankaiTraducao: "Corredor das Mil Vozes",
    bankaiPoder: "Rede Sonora Territorial: Projeta dezenas de canais acústicos com atordoamento sônico coordenado.",
    indices: { potencia: 7, alcance: 9, complexidade: 7, versatilidade: 8, custo: 5 }
  },
  {
    id: "zk-19-mokuren",
    nome: "Mokuren",
    kanji: "木蓮",
    traducao: "Magnólia",
    elemento: "Raízes de Reishi & Condução Energética",
    comando: "Crie raízes onde não existem, Mokuren",
    espirito: "Monge colossal de madeira viva.",
    formatoArma: "Espada viva que finca raízes condutoras no solo.",
    poder: "Conexão de Reishi: Transfere energia espiritual entre dois pontos enraizados.",
    bankaiNome: "Mokuren — Daijumyaku",
    bankaiKanji: "木蓮・大樹脈",
    bankaiTraducao: "Grande Veia da Árvore",
    bankaiPoder: "Rede Energética Continental: Redistribui ou drena Reiatsu em larga escala pelo solo.",
    indices: { potencia: 8, alcance: 9, complexidade: 8, versatilidade: 8, custo: 6 }
  },
  {
    id: "zk-20-hakugin",
    nome: "Hakugin",
    kanji: "白銀",
    traducao: "Prata Branca",
    elemento: "Análise Estrutural & Pontos de Tensão",
    comando: "Revele a forma escondida, Hakugin",
    espirito: "Ferreiro em oficina congelada.",
    formatoArma: "Lâmina analítica que identifica falhas internas de objetos tocados.",
    poder: "Visão Estrutural: Revela trincas e pontos fracos na matéria do adversário.",
    bankaiNome: "Hakugin — Shingyōro",
    bankaiKanji: "白銀・真形炉",
    bankaiTraducao: "Forja da Forma Verdadeira",
    bankaiPoder: "Desestruturação Ambiental: Mapeia e colapsa pontos de tensão em construções e defesas.",
    indices: { potencia: 8, alcance: 7, complexidade: 9, versatilidade: 8, custo: 6 }
  },
  {
    id: "zk-21-karasuame",
    nome: "Karasuame",
    kanji: "烏雨",
    traducao: "Chuva dos Corvos",
    elemento: "Aves Mensageiras & Extensão Sensorial",
    comando: "Desça sobre o mundo, Karasuame",
    espirito: "Um corvo gigante com três olhos que enxerga através das sombras.",
    formatoArma: "Katana de empunhadura emplumada que libera pequenas aves espirituais mensageiras.",
    poder: "Mensageiros das Trevas: Pequenas aves que transportam mensagens e espionam pontos cegos.",
    bankaiNome: "Karasuame — Manba Ten",
    bankaiKanji: "烏雨・万羽天",
    bankaiTraducao: "Céu das Mil Asas",
    bankaiPoder: "Milhares de corvos espirituais cobrem o campo, servindo como extensões visuais e cinéticas do usuário.",
    indices: { potencia: 7, alcance: 10, complexidade: 7, versatilidade: 9, custo: 6 }
  },
  {
    id: "zk-22-enko",
    nome: "Enkō",
    kanji: "円光",
    traducao: "Luz Circular",
    elemento: "Delimitação Geométrica & Preservação",
    comando: "Circunde aquilo que desejo proteger, Enkō",
    espirito: "Um sacerdote solene com um halo dourado giratório.",
    formatoArma: "Espada que desenha anéis luminosos no solo com propriedades de conservação.",
    poder: "Delimitação: Cria círculos onde uma propriedade física (fogo, integridade, barreira) é preservada intacta.",
    bankaiNome: "Enkō — Mankan Seīki",
    bankaiKanji: "円光・万環聖域",
    bankaiTraducao: "Santuário dos Mil Círculos",
    bankaiPoder: "Centenas de anéis concêntricos criando uma geometria de leis locais invioláveis no campo de batalha.",
    indices: { potencia: 8, alcance: 8, complexidade: 9, versatilidade: 9, custo: 7 }
  },
  {
    id: "zk-23-shakunetsurin",
    nome: "Shakunetsurin",
    kanji: "灼熱輪",
    traducao: "Anel Incandescente",
    elemento: "Transferência Rotacional & Energia Térmica",
    comando: "Gire até que o mundo aqueça, Shakunetsurin",
    espirito: "Um guerreiro coberto por anéis metálicos incandescentes.",
    formatoArma: "Chakram afiado de borda giratória incandescente.",
    poder: "Rotação Transferível: Transfere torque e rotação térmica violenta para qualquer objeto tocado.",
    bankaiNome: "Shakunetsurin — Tenkai",
    bankaiKanji: "灼熱輪・転界",
    bankaiTraducao: "Mundo Giratório",
    bankaiPoder: "Campos de rotação onde o próprio ambiente gira sob o padrão estabelecido pelo usuário.",
    indices: { potencia: 9, alcance: 7, complexidade: 7, versatilidade: 7, custo: 6 }
  },
  {
    id: "zk-24-aobotan",
    nome: "Aobotan",
    kanji: "青牡丹",
    traducao: "Peônia Azul",
    elemento: "Manifestação Espontânea & Preparação Tática",
    comando: "Floresça onde ninguém espera, Aobotan",
    espirito: "Mulher coberta por peônias azuis que desaparecem e brotam do vazio.",
    formatoArma: "Lâmina que planta botões de flores espirituais em qualquer superfície.",
    poder: "Botão Espontâneo: Cada flor libera um efeito predeterminado pelo usuário antes da batalha.",
    bankaiNome: "Aobotan — Senkakyō",
    bankaiKanji: "青牡丹・千花境",
    bankaiTraducao: "Domínio das Mil Flores",
    bankaiPoder: "Prepara dezenas de armadilhas e efeitos em centenas de flores para controle territorial absoluto.",
    indices: { potencia: 8, alcance: 8, complexidade: 9, versatilidade: 9, custo: 6 }
  },
  {
    id: "zk-25-kurogane",
    nome: "Kurogane",
    kanji: "黒鉄",
    traducao: "Ferro Negro",
    elemento: "Extração Mineral & Drenagem Geológica",
    comando: "Desperte das profundezas, Kurogane",
    espirito: "Um gigante mineral acorrentado em uma mina ancestral.",
    formatoArma: "Espada pesada que extrai Reishi de minerais e rochas tocadas.",
    poder: "Mineração de Reishi: Extrai energia do solo para revitalizar as reservas do usuário.",
    bankaiNome: "Kurogane — Shinsōro",
    bankaiKanji: "黒鉄・深層炉",
    bankaiTraducao: "Forja das Profundezas",
    bankaiPoder: "O terreno inteiro vira uma usina espiritual alimentando a força bruta e a resistência do usuário.",
    indices: { potencia: 9, alcance: 7, complexidade: 6, versatilidade: 8, custo: 7 }
  },
  {
    id: "zk-26-mizuhanabi",
    nome: "Mizuhanabi",
    kanji: "水花火",
    traducao: "Fogos d'Água",
    elemento: "Pressão Hidráulica & Esferas de Impacto",
    comando: "Exploda em silêncio, Mizuhanabi",
    espirito: "Menina brincando em um festival aquático submerso.",
    formatoArma: "Lâmina que gera esferas de água ultra-comprimida detonáveis.",
    poder: "Detonação Hidráulica: Esferas de alta pressão que estouram com ondas de choque cortantes.",
    bankaiNome: "Mizuhanabi — Shinkaisai",
    bankaiKanji: "水花火・深海祭",
    bankaiTraducao: "Festival do Mar Profundo",
    bankaiPoder: "Envolve o campo em correntes marítimas densas com gradientes esmagadores de pressão.",
    indices: { potencia: 9, alcance: 8, complexidade: 7, versatilidade: 8, custo: 7 }
  },
  {
    id: "zk-27-shorin",
    nome: "Shōrin",
    kanji: "鐘輪",
    traducao: "Anel do Sino",
    elemento: "Ecos Sônicos & Ondas Direcionais",
    comando: "Faça o mundo escutar, Shōrin",
    espirito: "Um monge meditando dentro de um monumental sino de bronze.",
    formatoArma: "Bastão metálico pesado que ressoa notas ensurdecedoras a cada golpe.",
    poder: "Golpe do Sino: Emite pulsos sonoros concentrados capazes de atordoar e quebrar matéria.",
    bankaiNome: "Shōrin — Tenkyōden",
    bankaiKanji: "鐘輪・天響殿",
    bankaiTraducao: "Palácio do Eco Celestial",
    bankaiPoder: "O campo rebate e amplifica cada emissão sônica, convergindo de todos os lados como uma tempestade acústica.",
    indices: { potencia: 8, alcance: 8, complexidade: 7, versatilidade: 8, custo: 6 }
  },
  {
    id: "zk-28-kobai",
    nome: "Kōbai",
    kanji: "紅梅",
    traducao: "Ameixeira Vermelha",
    elemento: "Persistência & Adaptação ao Dano",
    comando: "Floresça apesar do inverno, Kōbai",
    espirito: "Senhora idosa cultivando flores sob nevasca implacável.",
    formatoArma: "Katana que faz brotar pétalas vermelhas a cada ferimento ou dificuldade sofrida.",
    poder: "Memória da Dor: Reduz progressivamente o dano de ataques do mesmo tipo recebidos no combate.",
    bankaiNome: "Kōbai — Fukutsu Sentei",
    bankaiKanji: "紅梅・不屈千庭",
    bankaiTraducao: "Mil Jardins Indomáveis",
    bankaiPoder: "Converte experiências de impacto acumuladas em adaptação física e resistência quase invulnerável.",
    indices: { potencia: 8, alcance: 6, complexidade: 8, versatilidade: 9, custo: 7 }
  },
  {
    id: "zk-29-hoshigumo",
    nome: "Hoshigumo",
    kanji: "星蜘蛛",
    traducao: "Aranha Estelar",
    elemento: "Fios Espirituais & Teias de Reishi",
    comando: "Costure o céu, Hoshigumo",
    espirito: "Aranha celestial com corpo translúcido de constelações.",
    formatoArma: "Fios finíssimos de Reishi presos à guarda que mapeiam vibrações no ar.",
    poder: "Fios de Radar: Sente o menor movimento de massa que cruze as linhas no campo.",
    bankaiNome: "Hoshigumo — Tengaimō",
    bankaiKanji: "星蜘蛛・天蓋網",
    bankaiTraducao: "Teia do Firmamento",
    bankaiPoder: "Teia monumental cobrindo o céu com leitura perfeita de pressão, vetor e velocidade de tudo no espaço.",
    indices: { potencia: 7, alcance: 10, complexidade: 8, versatilidade: 9, custo: 6 }
  },
  {
    id: "zk-30-yomotsuhira",
    nome: "Yomotsuhira",
    kanji: "黄泉平",
    traducao: "Planície do Submundo",
    elemento: "Preservação de Estados & Restauração",
    comando: "Abra o caminho entre partidas e chegadas, Yomotsuhira",
    espirito: "Um barqueiro encapuzado navegando em rio infinito.",
    formatoArma: "Lâmina cerimonial que marca o estado físico exato de um objeto.",
    poder: "Marca de Estado: Pode reverter temporariamente um objeto marcado para seu estado anterior recente.",
    bankaiNome: "Yomotsuhira — Tosei",
    bankaiKanji: "黄泉平・渡世",
    bankaiTraducao: "Travessia Entre Estados",
    bankaiPoder: "Registra e transita entre múltiplos estados físicos simultâneos de matéria e terreno no combate.",
    indices: { potencia: 8, alcance: 8, complexidade: 10, versatilidade: 9, custo: 8 }
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { MASTER_ZANPAKUTO_CATALOG };
}
